# Name of Workflow
name: Production

# 3ggered at
on:
  push:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    # OS to be used
    runs-on: ubuntu-latest

    # Steps
    steps:
      # 1. Get code from repository
      - name: Checkout code
        uses: actions/checkout@v1

      # 2. Install Node 16
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # 3. Run npm install
      - run: npm install

      # 4. Run npm build to build the Next.js application
      - run: npm run build

      # 5. Test with the preferred Unit Testing Tool specified in package.json
      - name: Run jest
        uses: stefanoeb/jest-action@1.0.3
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

      # 6. Integration Testing (NOT YET IMPLEMENTED)

      # 7. Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          # get secrets from GitHub Repository Secrets
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
        with:
          # --prod argument deploys to the actual URL
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "PROD_NETLIFY_SITE_ID"]'
