# Name of Workflow
name: Staging

# 3ggered at
on:
  pull_request:
    branches:
      - staging

# Jobs to carry out
jobs:
  deploy:
    # OS to be used
    runs-on: ubuntu-latest

    # Steps
    steps:
      # 1. Get code from repository
      - name: Checkout code
        uses: actions/checkout@v1

      # 2. Install Node 16
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # 3. Run npm install
      - run: npm install

      # 4. Run npm build to build the Next.js application
      - run: npm run build
        env:
          CONTENTFUL_CDA_TOKEN: ${{ secrets.CONTENTFUL_CDA_TOKEN }}
          CONTENTFUL_SPACE_TOKEN: ${{ secrets.CONTENTFUL_SPACE_TOKEN }}
          CONTENTFUL_TEST_TOKEN: ${{ secrets.CONTENTFUL_TEST_TOKEN }}
          NOTION_MEMBERSHIP_APPLICATION: ${{ secrets.NOTION_MEMBERSHIP_APPLICATION }}
          NOTION_INTEGRATION_SECRET: ${{ secrets.NOTION_INTEGRATION_SECRET }}

        with:
          secrets: '["CONTENTFUL_CDA_TOKEN" , "CONTENTFUL_SPACE_TOKEN",  "CONTENTFUL_TEST_TOKEN", "NOTION_MEMBERSHIP_APPLICATION", "NOTION_INTEGRATION_SECRET"]'

      # 5. Test with the preferred Unit Testing Tool specified in package.json
      - name: Run jest
        uses: stefanoeb/jest-action@1.0.3
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

      # 6. Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          CONTENTFUL_CDA_TOKEN: ${{ secrets.CONTENTFUL_CDA_TOKEN }}
          CONTENTFUL_SPACE_TOKEN: ${{ secrets.CONTENTFUL_SPACE_TOKEN }}
          CONTENTFUL_TEST_TOKEN: ${{ secrets.CONTENTFUL_TEST_TOKEN }}
          NOTION_MEMBERSHIP_APPLICATION: ${{ secrets.NOTION_MEMBERSHIP_APPLICATION }}
          NOTION_INTEGRATION_SECRET: ${{ secrets.NOTION_INTEGRATION_SECRET }}

        with:
          # --prod argument deploys to the actual URL
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "DEV_NETLIFY_SITE_ID" , "CONTENTFUL_CDA_TOKEN" , "CONTENTFUL_SPACE_TOKEN",  "CONTENTFUL_TEST_TOKEN", "NOTION_MEMBERSHIP_APPLICATION", "NOTION_INTEGRATION_SECRET"]'
